<?php

declare(strict_types=1);

namespace Tests\Feature\Availability;

use App\Enums\AvailabilityRuleType;
use App\Enums\ServiceType;
use App\Http\Resources\AvailabilitySlotResource;
use App\Models\AvailabilityRule;
use App\Models\AvailabilitySlot;
use App\Models\Listing;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\Request;
use Tests\TestCase;

/**
 * BDD coverage for the per-rule show_duration toggle.
 *
 * When the vendor turns this on, the customer-facing slot picker renders
 * each slot's duration ("1h", "1h 30min", "3h") next to the time range
 * — computed live from end_time − start_time. This is a DISPLAY attribute,
 * not a price/quantity attribute: it is NOT snapshotted onto holds or
 * bookings. If the vendor flips it off mid-flight, subsequent renders
 * stop showing duration immediately (intended behaviour).
 *
 * Scope: tour, event, nautical (same as iteration 1). Accommodation
 * listings carry the field but their per-night booking flow ignores it.
 */
class AvailabilityRuleShowDurationTest extends TestCase
{
    use RefreshDatabase;

    /**
     * GIVEN: a rule created without show_duration explicitly set.
     * WHEN:  the rule materialises slots and the API resource serialises one.
     * THEN:  showDuration is false (column default) and durationMinutes
     *        is still computed and exposed (callers may want it for other
     *        display decisions even when the flag is off).
     *
     * Regression guard: every existing rule in production reads false after
     * the migration, so the picker continues to render exactly as today.
     */
    public function test_default_show_duration_is_false_for_new_rules(): void
    {
        $listing = Listing::factory()->create(['service_type' => ServiceType::TOUR]);

        $rule = AvailabilityRule::create([
            'listing_id' => $listing->id,
            'rule_type' => AvailabilityRuleType::WEEKLY,
            'days_of_week' => [Carbon::MONDAY],
            'time_slots' => [
                ['start_time' => '09:00:00', 'end_time' => '10:00:00', 'capacity' => 5],
            ],
            'is_active' => true,
        ]);

        $this->assertFalse((bool) $rule->show_duration);

        $slot = AvailabilitySlot::where('listing_id', $listing->id)->firstOrFail();
        $slot->setRelation('availabilityRule', $rule);
        $slot->setRelation('listing', $listing);

        $payload = (new AvailabilitySlotResource($slot))->toArray(Request::create('/'));

        $this->assertFalse(
            $payload['showDuration'],
            'showDuration must default to false so existing listings render exactly as today.',
        );
        $this->assertSame(60, (int) $payload['durationMinutes']);
    }

    /**
     * GIVEN: a vendor enables show_duration on a rule.
     * WHEN:  the slots are serialised.
     * THEN:  every slot generated by THAT rule carries showDuration=true and
     *        the correct durationMinutes.
     */
    public function test_show_duration_true_propagates_to_slots(): void
    {
        $listing = Listing::factory()->create(['service_type' => ServiceType::TOUR]);
        $monday = Carbon::today()->next(Carbon::MONDAY);

        $rule = AvailabilityRule::create([
            'listing_id' => $listing->id,
            'rule_type' => AvailabilityRuleType::WEEKLY,
            'days_of_week' => [Carbon::MONDAY],
            'time_slots' => [
                ['start_time' => '09:00:00', 'end_time' => '10:00:00', 'capacity' => 5],
                ['start_time' => '14:00:00', 'end_time' => '17:00:00', 'capacity' => 5],
            ],
            'show_duration' => true,
            'start_date' => $monday->copy(),
            'end_date' => $monday->copy(),
            'is_active' => true,
        ]);

        // Scope to the single Monday so we get exactly two slots — the rule
        // would otherwise generate 26 Mondays × 2 slots over the 180-day window.
        $slots = AvailabilitySlot::where('listing_id', $listing->id)
            ->whereDate('date', $monday->toDateString())
            ->orderBy('start_time')->get();

        $this->assertCount(2, $slots, 'Two slots must materialise for that single Monday.');

        foreach ($slots as $slot) {
            $slot->setRelation('availabilityRule', $rule);
            $slot->setRelation('listing', $listing);
            $payload = (new AvailabilitySlotResource($slot))->toArray(Request::create('/'));
            $this->assertTrue($payload['showDuration']);
        }

        // 09:00 → 10:00 = 60min, 14:00 → 17:00 = 180min
        $first = (new AvailabilitySlotResource($slots[0]))->toArray(Request::create('/'));
        $second = (new AvailabilitySlotResource($slots[1]))->toArray(Request::create('/'));
        $this->assertSame(60, (int) $first['durationMinutes']);
        $this->assertSame(180, (int) $second['durationMinutes']);
    }

    /**
     * GIVEN: slots with various time-window sizes.
     * WHEN:  durationMinutes is computed.
     * THEN:  the value matches end_time − start_time exactly, across the full
     *        range of legal slot sizes (1 minute to 23h 59min).
     */
    public function test_duration_minutes_is_end_minus_start_for_all_sizes(): void
    {
        $listing = Listing::factory()->create(['service_type' => ServiceType::TOUR]);

        $cases = [
            ['09:00:00', '09:01:00', 1],         // smallest legal slot
            ['09:00:00', '09:30:00', 30],        // half hour
            ['09:00:00', '10:00:00', 60],        // one hour
            ['09:00:00', '10:30:00', 90],        // one hour thirty
            ['08:00:00', '16:00:00', 480],       // eight hours
            ['00:00:00', '23:59:00', 1439],      // largest legal slot
        ];

        foreach ($cases as $i => [$start, $end, $expectedMinutes]) {
            $rule = AvailabilityRule::create([
                'listing_id' => $listing->id,
                'rule_type' => AvailabilityRuleType::SPECIFIC_DATES,
                'specific_dates' => [Carbon::today()->addDays($i + 1)->toDateString()],
                'time_slots' => [
                    ['start_time' => $start, 'end_time' => $end, 'capacity' => 1],
                ],
                'show_duration' => true,
                'is_active' => true,
            ]);

            $slot = AvailabilitySlot::where('listing_id', $listing->id)
                ->whereDate('date', Carbon::today()->addDays($i + 1))
                ->firstOrFail();
            $slot->setRelation('availabilityRule', $rule);
            $slot->setRelation('listing', $listing);

            $payload = (new AvailabilitySlotResource($slot))->toArray(Request::create('/'));
            $this->assertSame(
                $expectedMinutes,
                (int) $payload['durationMinutes'],
                "Slot {$start} → {$end} should compute to {$expectedMinutes} minutes.",
            );
        }
    }

    /**
     * GIVEN: two rules on the same listing, ON for rule A and OFF for rule B,
     *        each producing slots on the same date.
     * WHEN:  slots are serialised.
     * THEN:  each slot reflects ITS OWN rule's show_duration setting — the
     *        flag is a per-rule attribute, not a per-listing attribute.
     */
    public function test_mixed_rules_carry_independent_show_duration_per_slot(): void
    {
        $listing = Listing::factory()->create(['service_type' => ServiceType::TOUR]);
        $monday = Carbon::today()->next(Carbon::MONDAY);

        $ruleOn = AvailabilityRule::create([
            'listing_id' => $listing->id,
            'rule_type' => AvailabilityRuleType::WEEKLY,
            'days_of_week' => [Carbon::MONDAY],
            'time_slots' => [['start_time' => '09:00:00', 'end_time' => '10:00:00', 'capacity' => 5]],
            'show_duration' => true,
            'start_date' => $monday->copy(),
            'end_date' => $monday->copy(),
            'is_active' => true,
        ]);

        $ruleOff = AvailabilityRule::create([
            'listing_id' => $listing->id,
            'rule_type' => AvailabilityRuleType::WEEKLY,
            'days_of_week' => [Carbon::MONDAY],
            'time_slots' => [['start_time' => '14:00:00', 'end_time' => '15:00:00', 'capacity' => 5]],
            'show_duration' => false,
            'start_date' => $monday->copy(),
            'end_date' => $monday->copy(),
            'is_active' => true,
        ]);

        $morning = AvailabilitySlot::where('listing_id', $listing->id)
            ->whereTime('start_time', '09:00:00')
            ->firstOrFail();
        $afternoon = AvailabilitySlot::where('listing_id', $listing->id)
            ->whereTime('start_time', '14:00:00')
            ->firstOrFail();

        $morning->setRelation('availabilityRule', $ruleOn);
        $morning->setRelation('listing', $listing);
        $afternoon->setRelation('availabilityRule', $ruleOff);
        $afternoon->setRelation('listing', $listing);

        $morningPayload = (new AvailabilitySlotResource($morning))->toArray(Request::create('/'));
        $afternoonPayload = (new AvailabilitySlotResource($afternoon))->toArray(Request::create('/'));

        $this->assertTrue($morningPayload['showDuration'], 'Morning rule has flag ON.');
        $this->assertFalse($afternoonPayload['showDuration'], 'Afternoon rule has flag OFF.');
    }

    /**
     * GIVEN: a legacy single-time rule (no time_slots JSON, only start_time/end_time/capacity columns)
     *        with show_duration=true.
     * WHEN:  the rule materialises a slot via getEffectiveTimeSlots().
     * THEN:  the synthesised slot still inherits showDuration=true and reports
     *        a correct durationMinutes — backward compat for legacy data.
     */
    public function test_legacy_single_time_rule_supports_show_duration(): void
    {
        $listing = Listing::factory()->create(['service_type' => ServiceType::TOUR]);

        $rule = AvailabilityRule::create([
            'listing_id' => $listing->id,
            'rule_type' => AvailabilityRuleType::WEEKLY,
            'days_of_week' => [Carbon::MONDAY],
            'start_time' => '10:00:00',
            'end_time' => '13:00:00',
            'capacity' => 8,
            'show_duration' => true,
            'is_active' => true,
        ]);
        // Force null time_slots so the legacy path is exercised
        // (saved() observer regenerates slots from the synthesised entry).
        $rule->forceFill(['time_slots' => null])->save();

        $slot = AvailabilitySlot::where('listing_id', $listing->id)->first();
        $this->assertNotNull($slot, 'Legacy rule must still produce a slot.');

        $slot->setRelation('availabilityRule', $rule);
        $slot->setRelation('listing', $listing);
        $payload = (new AvailabilitySlotResource($slot))->toArray(Request::create('/'));

        $this->assertTrue($payload['showDuration']);
        $this->assertSame(180, (int) $payload['durationMinutes']);
    }

    /**
     * GIVEN: an accommodation listing with a rule whose show_duration flag is true.
     * WHEN:  the rule's slots are serialised.
     * THEN:  the field IS present (column lives on every rule) but the
     *        accommodation listing's per-night booking flow does NOT
     *        consume it for any pricing or capacity decision. The flag is
     *        purely a slot-picker concern.
     *
     * Explicit regression guard mirroring the iteration-1 accommodation
     * regression test — keeps accommodation flow surface-area unchanged.
     */
    public function test_accommodation_rule_can_carry_show_duration_without_breaking_per_night_flow(): void
    {
        $listing = Listing::factory()->create([
            'service_type' => ServiceType::ACCOMMODATION,
        ]);

        $rule = AvailabilityRule::create([
            'listing_id' => $listing->id,
            'rule_type' => AvailabilityRuleType::DAILY,
            'days_of_week' => [Carbon::MONDAY, Carbon::TUESDAY, Carbon::WEDNESDAY,
                Carbon::THURSDAY, Carbon::FRIDAY, Carbon::SATURDAY, Carbon::SUNDAY],
            'capacity' => 1,
            'show_duration' => true,
            'is_active' => true,
        ]);

        $this->assertTrue((bool) $rule->show_duration, 'Field accepts true on accommodation rules.');

        // Sanity: AccommodationBookingService::calculatePrice signature is
        // unchanged — show_duration is not in its parameters or return shape.
        $reflection = new \ReflectionMethod(
            \App\Services\AccommodationBookingService::class,
            'calculatePrice',
        );
        $params = collect($reflection->getParameters())->map(fn ($p) => $p->getName())->all();
        $this->assertNotContains(
            'show_duration',
            $params,
            'Accommodation pricing must remain show_duration-unaware. '
            .'If anyone ever wires it in, that is a separate ticket.',
        );
    }

    /**
     * GIVEN: a tour rule that combines BOTH price_overrides (iteration 1)
     *        and show_duration=true (iteration 3).
     * WHEN:  the slot is serialised.
     * THEN:  both fields are present and correct simultaneously — the two
     *        features are independent and don't collide on the resource.
     */
    public function test_show_duration_coexists_with_price_overrides_on_the_same_slot(): void
    {
        $listing = Listing::factory()->create([
            'service_type' => ServiceType::TOUR,
            'pricing' => [
                'person_types' => [
                    ['key' => 'adult', 'tnd_price' => 50, 'eur_price' => 15],
                    ['key' => 'child', 'tnd_price' => 30, 'eur_price' => 10],
                ],
            ],
        ]);

        $rule = AvailabilityRule::create([
            'listing_id' => $listing->id,
            'rule_type' => AvailabilityRuleType::WEEKLY,
            'days_of_week' => [Carbon::MONDAY],
            'time_slots' => [
                [
                    'start_time' => '09:00:00',
                    'end_time' => '12:00:00',
                    'capacity' => 4,
                    'price_overrides' => [
                        'person_types' => [
                            ['key' => 'adult', 'tnd_price' => 120, 'eur_price' => 40],
                        ],
                    ],
                ],
            ],
            'show_duration' => true,
            'is_active' => true,
        ]);

        $slot = AvailabilitySlot::where('listing_id', $listing->id)->firstOrFail();
        $slot->setRelation('availabilityRule', $rule);
        $slot->setRelation('listing', $listing);

        $payload = (new AvailabilitySlotResource($slot))->toArray(Request::create('/'));

        // Iteration 1 fields still correct.
        $this->assertNotNull($payload['priceOverrides']);
        $this->assertSame(120, (int) $payload['priceOverrides']['person_types'][0]['tnd_price']);
        $this->assertSame(120.0, (float) $payload['effectivePrices']['TND']['adult']);
        $this->assertSame(30.0, (float) $payload['effectivePrices']['TND']['child']);

        // Iteration 3 fields are additive.
        $this->assertTrue($payload['showDuration']);
        $this->assertSame(180, (int) $payload['durationMinutes']);
    }
}
